#!/bin/bash

# Check if the input file is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <input_file.cc>"
  exit 1
fi

INPUT_FILE="$(pwd)/scratch/12241300/$1"

# Run the Python script to generate .cc files with different DataRate and Delay
python3 q2_4.py "$INPUT_FILE"

# Array of different .pcap files generated by the Python script
pcap_files=("iteration_1-1-0.pcap" "iteration_2-1-0.pcap" "iteration_3-1-0.pcap" "iteration_4-1-0.pcap")
datarates=("5Mbps" "10Mbps" "5Mbps" "10Mbps")
delays=("5ms" "5ms" "2ms" "2ms")

# Header for output table
echo "============================================================"
echo "| DataRate | Delay | Throughput (Bytes/sec) | TcpVegas |"
echo "============================================================"

# Loop through each pcap file to calculate throughput
for i in "${!pcap_files[@]}"; do
  pcap_file="${pcap_files[i]}"
  
  # Store tshark output in a variable with IP filter and frame length
  output=$(tshark -r "$pcap_file" -Y "ip.src==10.1.1.1" -T fields -e frame.len)

  # Calculate the sum of frame lengths (bytes)
  bytes=$(echo "$output" | awk '{sum += $1} END {print sum}')

  echo "Parsed Bytes: $bytes"
  
  # Calculate throughput (Bytes/sec)
  duration=20.0  # Fixed duration as per instruction
  throughput=$(echo "scale=2; (8 * $bytes) / ($duration * 1000000)" | bc -l)
  
  # Print DataRate, Delay, and Throughput in the table format
  echo "| ${datarates[i]} | ${delays[i]} | Throughput : $throughput Mbps |"
done

echo "============================================================"

